Revert "Migrate to Maven"

diff --git a/refine b/refine
--- a/refine
+++ b/refine
@@ -297,33 +297,32 @@ tools_prepare() {
         mkdir $REFINE_TOOLS_DIR || error "Error while making directory $REFINE_TOOLS_DIR"
     fi
 }
-
-mvn_prepare() {
+                        
+ant_prepare() {
     tools_prepare
 
-    MVN_VERSION="3.2.2"
-    MVN_URL="https://archive.apache.org/dist/maven/binaries/apache-maven-${MVN_VERSION}-bin.tar.gz"
-    MVN_FILE=`echo $MVN_URL | sed 's|.*/||'`
-    MVN_DIR="apache-maven-${MVN_VERSION}"
-
-    MVN="`which mvn 2> /dev/null`"
-   
-    if [ -z "$MVN" ] ; then
-        if [ -z "$MVN_HOME" ] ; then
+    ANT_VERSION="1.9.0"
+    ANT_URL="http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz"
+    ANT_FILE=`echo $ANT_URL | sed 's|.*/||'`
+    ANT_DIR="apache-ant-${ANT_VERSION}"
+    
+    ANT="`which ant 2> /dev/null`"
+    if [ -z "$ANT" ] ; then
+        if [ -z "$ANT_HOME" ] ; then
             cd $REFINE_TOOLS_DIR
-                if [ ! -f "$MVN_FILE" ] ; then
-                    download $MVN_URL $MVN_FILE
+                if [ ! -f "$ANT_FILE" ] ; then
+                    download $ANT_URL $ANT_FILE
                 fi
-                if [ ! -d "$MVN_DIR" ] ; then
-                    tar xzf $MVN_FILE -C . || error "Error while expanding $MVN_FILE"
+                if [ ! -d "$ANT_DIR" ] ; then
+                    tar xzf $ANT_FILE -C . || error "Error while expanding $ANT_FILE"
                 fi
-                export MVN_HOME="`pwd`/$MVN_DIR"
+                export ANT_HOME="`pwd`/$ANT_DIR"
                 if [ "$OS" = "windows" ] ; then
-                    export MVN_HOME=`cygpath --unix "$MVN_HOME"`
+                    export ANT_HOME=`cygpath --unix "$ANT_HOME"`
                 fi
             cd ..
         fi
-        MVN="$MVN_HOME/bin/mvn"
+        ANT="$ANT_HOME/bin/ant"
     fi
 }
 
@@ -451,10 +450,12 @@ jslint_prepare() {
             
 # ----------------------------------------------------------------------------------------------
 
-mvn() {
-    mvn_prepare   
+ant() {
+    ant_prepare   
     
-    "$MVN" $MVN_PARAMS -Dversion="$VERSION" -Dfull_version="$FULL_VERSION"  $1 || error "Error while running maven task '$1'"
+    #export ANT_OPTS="-Xmx1024M"
+    
+    "$ANT" -f build.xml $ANT_PARAMS -Dversion="$VERSION" -Dfull_version="$FULL_VERSION"  $1 || error "Error while running ant task '$1'"
 }
 
 # ----------------------------------------------------------------------------------------------
@@ -488,9 +489,8 @@ windows_dist() {
 
     launch4j_prepare
     
-    MVN_PARAMS="-Dlaunch4j.dir=${REFINE_TOOLS_DIR}/${LAUNCH4J_DIR}"
-    # TODO update this for Maven
-    $MVN windows
+    ANT_PARAMS="-Dlaunch4j.dir=${REFINE_TOOLS_DIR}/${LAUNCH4J_DIR}"
+    ant windows
 }
 
 linux_dist() {
@@ -498,12 +498,10 @@ linux_dist() {
     get_version $1
     get_revision
     
-    # TODO update this for Maven
-    $MVN linux
+    ant linux
 }
     
 mac_dist() {
-    # TODO update this for Maven, maybe with https://github.com/federkasten/appbundle-maven-plugin ?
     check_macosx
     dist_prepare
     get_version $1
@@ -574,8 +572,9 @@ mac_dist() {
 }
 
 test() {
-    mvn_prepare
-    $MVN test
+    server_test $1
+    ui_test $1 
+    extensions_test $1
 }
 
 ui_test() {
@@ -617,13 +616,11 @@ ui_test() {
 }
 
 server_test() {
-    mvn_prepare
-    $MVN test -f main
+    ant server_test
 }
 
 extensions_test() {
-    mvn_prepare
-    $MVN test -f extensions
+    ant extensions_test
 }
 
 run() {
@@ -638,13 +635,11 @@ run() {
     if [ ! -d $REFINE_CLASSES_DIR ] ; then
         IS_JAR=`ls $REFINE_LIB_DIR | grep openrefine`
         if [ -z "$IS_JAR" ] ; then
-            mvn_prepare
-            $MVN process-resources
-            $MVN compile test-compile
+            ant build
             echo ""
         fi
     fi
-
+            
     if [ -d $REFINE_CLASSES_DIR ] ; then
         add_option "-Drefine.autoreload=true -Dbutterfly.autoreload=true"
     fi
@@ -681,7 +676,7 @@ run() {
 
     RUN_CMD="$JAVA -cp $CLASSPATH $OPTS com.google.refine.Refine"
 
-    echo "$RUN_CMD"
+    #echo "$RUN_CMD"
     #echo ""
   
     echo "Starting OpenRefine at 'http://${REFINE_HOST}:${REFINE_PORT}/'"
@@ -698,8 +693,7 @@ run() {
 broker_build() {
     build_prepare
     get_revision    
-    # TODO migrate to Maven
-    $MVN prepare_broker
+    ant prepare_broker
 }
 
 broker_run() {
@@ -721,8 +715,7 @@ broker_run() {
     add_option "-Drefine.port=$REFINE_PORT"
     add_option "-Drefine.host=0.0.0.0"
                     
-    LIB_PATHS=`cat server/classpath.txt`
-    CLASSPATH="$REFINE_CLASSES_DIR${SEP}$LIB_PATHS"
+    CLASSPATH="$REFINE_CLASSES_DIR${SEP}$REFINE_LIB_DIR/*"
 
     RUN_CMD="$JAVA -cp $CLASSPATH $OPTS com.google.refine.Refine"
 
@@ -745,18 +738,17 @@ broker_appengine_build() {
     appengine_prepare
     get_revision
     
-    MVN_PARAMS="-Dappengine.sdk.dir=${APPENGINE_HOME}"
+    ANT_PARAMS="-Dappengine.sdk.dir=${APPENGINE_HOME}"
 
     if [ "$1" ] ; then
-        MVN_PARAMS="$MVN_PARAMS -Dappengine.app_id=$1"
+        ANT_PARAMS="$ANT_PARAMS -Dappengine.app_id=$1"
     fi
     
     if [ "$2" ] ; then
-        MVN_PARAMS="$MVN_PARAMS -Dappengine.version=$2"
+        ANT_PARAMS="$ANT_PARAMS -Dappengine.version=$2"
     fi
         
-    # TODO migrate this to Maven
-    $MVN prepare_broker_appengine
+    ant prepare_broker_appengine
 }
        
 broker_appengine_upload() {
@@ -772,7 +764,7 @@ broker_appengine_run() {
 findbugs() {
     findbugs_prepare
     
-    MVN_PARAMS="-Dfindbugs.dir=${REFINE_TOOLS_DIR}/${FINDBUGS_DIR}"
+    ANT_PARAMS="-Dfindbugs.dir=${REFINE_TOOLS_DIR}/${FINDBUGS_DIR}"
     ant findbugs
     
     display "$REFINE_BUILD_DIR/reports/findbugs.html"
@@ -970,7 +962,7 @@ if [ -z "$REFINE_CLASSES_DIR" ] ; then
 fi
 
 if [ -z "$REFINE_LIB_DIR" ] ; then
-    REFINE_LIB_DIR="server/target/lib"
+    REFINE_LIB_DIR="server/lib"
 fi
 
 if [ -z "$REFINE_BUILD_DIR" ] ; then
@@ -1005,10 +997,10 @@ add_option "-Dpython.cachedir=$HOME/.local/share/google/refine/cachedir"
 
 # ----- Respond to the action given --------------------------------------------
 case "$ACTION" in
-  build) build_prepare; mvn process-resources; mvn compile test-compile;;
-  clean) mvn clean;;
+  build) build_prepare; ant build;;
+  clean) ant clean;;
   whitespace) whitespace $1;;
-  distclean) mvn distclean;;
+  distclean) ant distclean;;
   test) test $1;;  
   tests) test $1;;  
   ui_test) ui_test $1;;  
